name: Issue assignment

on:
    issues:
        types: [opened]
        comment: 
          - 'self-assign'

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  numOfAssignee: 1 
                  allowSelfAssign: True
